Repository AstroHuntsman/huntsman-pocs, pull requests merged in 2018-10, with the labels that each got.

#76 Fix Travis CI, coverage & coveralls
  .coveragerc
  .gitignore
  .travis.yml
  conf_files/huntsman.yaml
  conf_files/state_machine.yaml
  huntsman/tests/test_huntsman.py
  matplotlibrc
  resources/state_table/huntsman.yaml
Labels: enhancement, high priority

#78 Further fixing of Travis
  .travis.yml
Labels: bug, high priority

#75 Add coarse focus to evening calibrations
  states/huntsman/calibrating.py
Labels: enhancement, observing logic

#80 Add support for distributed Cameras
  .travis.yml
  conf_files/pyro_camera.yaml
  huntsman/camera/__init__.py
  huntsman/camera/pyro.py
  huntsman/tests/conftest.py
  huntsman/tests/test_aardvark.py
  huntsman/tests/test_camera.py
  huntsman/tests/test_huntsman.py
  huntsman/utils/__init__.py
  huntsman/utils/pyro/__init__.py
  requirements.txt
  scripts/pyro_camera_server.py
  scripts/pyro_name_server.py
Labels: camera, enhancement, high priority

#87 Properly reread targets file
  conf_files/huntsman.yaml
  states/huntsman/scheduling.py
Labels: bug

#88 Fixing pyro result
  huntsman/camera/pyro.py
Labels: bug

#90 Wait for autofocus events
  states/huntsman/calibrating.py
Labels: bug
